<?php
if (!defined("HDPHP_PATH"))exit('No direct script access allowed');
return array(
	array(
		'name'=>'后台首页',
		'ico'=>'icon-home',
		'subnav'=>array(
			array(
			'url'=>U('Admin/Index/welcome'),
			'name'=>'网站信息查看'
			),
		)
	),
	array(
		'name'=>'商品类型',
		'ico'=>'icon-calendar',
		'subnav'=>array(
			array(
				'url'=>U('Admin/Type/index'),
				'name'=>'商品类型列表'
			),
			array(
				'url'=>U('Admin/Type/addType'),
				'name'=>'添加商品类型'
			),
		)
	),
	array(
		'name'=>'商品分类',
		'ico'=>' icon-list-alt',
		'subnav'=>array(
			array(
				'url'=>U('Admin/Category/index'),
				'name'=>'商品分类列表'
			),
			array(
				'url'=>U('Admin/Category/add'),
				'name'=>'添加商品分类'
			),
		)
	),
	array(
		'name'=>'商品管理',
		'ico'=>' icon-gift',
		'subnav'=>array(
			array(
				'url'=>U('Admin/Goods/index'),
				'name'=>'商品列表'
			),
			array(
				'url'=>U('Admin/Goods/add'),
				'name'=>'添加商品'
			),
			array(
				'url'=>U('Admin/Goods/showGoods'),
				'name'=>'橱窗商品'
			),
		)
	),
	array(
		'name'=>'订单管理',
		'ico'=>' icon-list-alt',
		'subnav'=>array(
			array(
				'url'=>U('Admin/Order/index'),
				'name'=>'所有订单'
			),
			array(
				'url'=>U('Admin/Order/index/status/1'),
				'name'=>'已付款订单'
			),
			array(
				'url'=>U('Admin/Order/index/status/0'),
				'name'=>'未付款订单'
			),
		)
	),
	array(
		'name'=>'导航管理',
		'ico'=>'icon-th',
		'subnav'=>array(
			array(
				'url'=>U('Admin/Nav/index'),
				'name'=>'导航列表'
			),
			array(
				'url'=>U('Admin/Nav/add'),
				'name'=>'添加导航'
			),

		),
	),
	array(
		'name'=>'首页轮播图管理',
		'ico'=>'icon-picture',
		'subnav'=>array(
			array(
				'url'=>U('Admin/Banner/index'),
				'name'=>'轮播图列表'
			),
			array(
				'url'=>U('Admin/Banner/add'),
				'name'=>'添加轮播图'
			),

		),
	),
);
?>